import type { LolCard, LolRarity, LolRegion, PrintType } from '../../types';

// Riot Data Dragon — champion loading screen art (portrait crop, official CDN)
const ART = (name: string, n = 0) =>
  `https://ddragon.leagueoflegends.com/cdn/img/champion/loading/${name}_${n}.jpg`;

export const LOL_SETS: Record<string, { name: string; version: string; year: number }> = {
  'set-1': { name: 'Foundations',         version: '1.0', year: 2024 },
  'set-2': { name: 'Call of the Mountain', version: '2.0', year: 2024 },
  'set-3': { name: 'Worldwalker',          version: '3.0', year: 2025 },
  'set-4': { name: 'Forces of Beyond',     version: '4.0', year: 2025 },
};

// Each champion/spell appears multiple times — once per printing
// printType represents the card "version" the user can filter by
const make = (
  base: Omit<LolCard, 'game' | 'printType' | 'cardNumber'>,
  printings: Array<{ printType: PrintType; cardNumber: string }>
): LolCard[] =>
  printings.map((p) => ({
    ...base,
    game: 'lol' as const,
    printType: p.printType,
    cardNumber: p.cardNumber,
    id: `${base.id}-${p.printType.toLowerCase().replace(/\s/g, '-')}`,
  }));

const BASE_CARDS: Omit<LolCard, 'game' | 'printType' | 'cardNumber' | 'id'>[] = [
  // ── Set 1: Foundations ────────────────────────────────────────────────────
  {
    name: 'Jinx',
    type: 'Champion',
    rarity: 'Legendary' as LolRarity,
    region: 'Zaun' as LolRegion,
    setId: 'set-1',
    setName: 'Foundations',
    setVersion: '1.0',
    cost: 4, attack: 3, health: 4,
    description: 'When you play your 4th card in a round, Jinx levels up and gains +2/+0 and Overwhelm.',
    flavorText: '"Have I told you about the time I almost blew up a whole city?"',
    imageUrl: ART('Jinx'),
    keywords: ['Quick Attack', 'Support'],
  },
  {
    name: 'Lux',
    type: 'Champion',
    rarity: 'Legendary' as LolRarity,
    region: 'Demacia' as LolRegion,
    setId: 'set-1',
    setName: 'Foundations',
    setVersion: '1.0',
    cost: 6, attack: 4, health: 5,
    description: 'Barrier. When Lux is summoned, create a Final Spark in your hand.',
    flavorText: '"Light cannot exist without shadow."',
    imageUrl: ART('Lux'),
    keywords: ['Barrier', 'Enlightened'],
  },
  {
    name: 'Darius',
    type: 'Champion',
    rarity: 'Legendary' as LolRarity,
    region: 'Noxus' as LolRegion,
    setId: 'set-1',
    setName: 'Foundations',
    setVersion: '1.0',
    cost: 6, attack: 7, health: 6,
    description: 'Overwhelm. When Darius kills a unit, he deals 2 to the enemy Nexus.',
    flavorText: '"The weak have no place in Noxus."',
    imageUrl: ART('Darius'),
    keywords: ['Overwhelm'],
  },
  {
    name: 'Ashe',
    type: 'Champion',
    rarity: 'Legendary' as LolRarity,
    region: 'Freljord' as LolRegion,
    setId: 'set-1',
    setName: 'Foundations',
    setVersion: '1.0',
    cost: 4, attack: 3, health: 3,
    description: 'Frostbite. When Ashe attacks, grant Frostbite to the weakest enemy.',
    imageUrl: ART('Ashe'),
    keywords: ['Frostbite', 'Overwhelm'],
  },
  {
    name: 'Ezreal',
    type: 'Champion',
    rarity: 'Legendary' as LolRarity,
    region: 'Piltover' as LolRegion,
    setId: 'set-1',
    setName: 'Foundations',
    setVersion: '1.0',
    cost: 3, attack: 3, health: 2,
    description: 'Elusive. When you cast a spell, deal 1 to anything.',
    flavorText: '"There is so much more to see."',
    imageUrl: ART('Ezreal'),
    keywords: ['Elusive', 'Reputation'],
  },
  {
    name: 'Garen',
    type: 'Champion',
    rarity: 'Legendary' as LolRarity,
    region: 'Demacia' as LolRegion,
    setId: 'set-1',
    setName: 'Foundations',
    setVersion: '1.0',
    cost: 5, attack: 5, health: 6,
    description: 'Challenger, Regeneration. When Garen levels up, summon 2 Soldiers.',
    flavorText: '"Demacia!"',
    imageUrl: ART('Garen'),
    keywords: ['Challenger', 'Regeneration'],
  },
  {
    name: 'Vi',
    type: 'Champion',
    rarity: 'Legendary' as LolRarity,
    region: 'Piltover' as LolRegion,
    setId: 'set-1',
    setName: 'Foundations',
    setVersion: '1.0',
    cost: 5, attack: 6, health: 5,
    description: 'Challenger, Tough. When Vi attacks, stun the blocker.',
    flavorText: '"Rules are made to be broken."',
    imageUrl: ART('Vi'),
    keywords: ['Challenger', 'Tough'],
  },
  {
    name: 'Mystic Shot',
    type: 'Spell',
    rarity: 'Common' as LolRarity,
    region: 'Piltover' as LolRegion,
    setId: 'set-1',
    setName: 'Foundations',
    setVersion: '1.0',
    cost: 2,
    description: "Deal 2 to anything. Costs 1 less for each time you've targeted something this round.",
    imageUrl: ART('Ezreal', 1),
    keywords: ['Fast'],
  },
  {
    name: 'Decimate',
    type: 'Spell',
    rarity: 'Rare' as LolRarity,
    region: 'Noxus' as LolRegion,
    setId: 'set-1',
    setName: 'Foundations',
    setVersion: '1.0',
    cost: 4,
    description: 'Deal 4 to all enemies and 2 to your Nexus.',
    imageUrl: ART('Darius', 1),
    keywords: ['Slow'],
  },
  {
    name: "Anivia's Eggblock",
    type: 'Landmark',
    rarity: 'Epic' as LolRarity,
    region: 'Freljord' as LolRegion,
    setId: 'set-1',
    setName: 'Foundations',
    setVersion: '1.0',
    cost: 3,
    description: 'Round End: Deal 1 to all enemies. When destroyed, summon Anivia.',
    imageUrl: ART('Anivia'),
    keywords: ['Landmark'],
  },
  // ── Set 2: Call of the Mountain ───────────────────────────────────────────
  {
    name: 'Leona',
    type: 'Champion',
    rarity: 'Legendary' as LolRarity,
    region: 'Targon' as LolRegion,
    setId: 'set-2',
    setName: 'Call of the Mountain',
    setVersion: '2.0',
    cost: 5, attack: 4, health: 5,
    description: 'Tough, Challenger. When Leona attacks, stun the blocker at start of combat.',
    flavorText: '"Feel the wrath of the Solari."',
    imageUrl: ART('Leona'),
    keywords: ['Tough', 'Challenger', 'Eclipse'],
  },
  {
    name: 'Diana',
    type: 'Champion',
    rarity: 'Legendary' as LolRarity,
    region: 'Targon' as LolRegion,
    setId: 'set-2',
    setName: 'Call of the Mountain',
    setVersion: '2.0',
    cost: 4, attack: 4, health: 3,
    description: 'Elusive. When Diana levels up, summon 2 Moonbeams.',
    imageUrl: ART('Diana'),
    keywords: ['Elusive', 'Nightfall'],
  },
  {
    name: 'Malphite',
    type: 'Champion',
    rarity: 'Legendary' as LolRarity,
    region: 'Targon' as LolRegion,
    setId: 'set-2',
    setName: 'Call of the Mountain',
    setVersion: '2.0',
    cost: 7, attack: 5, health: 9,
    description: 'Tough. When Malphite levels up, deal 2 to all enemies and stun them.',
    imageUrl: ART('Malphite'),
    keywords: ['Tough', 'Immovable'],
  },
  {
    name: 'Soraka',
    type: 'Support',
    rarity: 'Epic' as LolRarity,
    region: 'Targon' as LolRegion,
    setId: 'set-2',
    setName: 'Call of the Mountain',
    setVersion: '2.0',
    cost: 3, attack: 1, health: 4,
    description: 'When you heal the Nexus or allies, deal 1 to the enemy Nexus per heal.',
    imageUrl: ART('Soraka'),
    keywords: ['Regeneration'],
  },
  {
    name: 'Cosmic Inspiration',
    type: 'Spell',
    rarity: 'Rare' as LolRarity,
    region: 'Targon' as LolRegion,
    setId: 'set-2',
    setName: 'Call of the Mountain',
    setVersion: '2.0',
    cost: 5,
    description: 'Grant all allies +2/+2 and a random keyword.',
    imageUrl: ART('Soraka', 1),
    keywords: ['Burst'],
  },
  {
    name: 'The Grand Plaza',
    type: 'Landmark',
    rarity: 'Epic' as LolRarity,
    region: 'Targon' as LolRegion,
    setId: 'set-2',
    setName: 'Call of the Mountain',
    setVersion: '2.0',
    cost: 4,
    description: 'When you summon a unit, it gains Challenger this round.',
    imageUrl: ART('Leona', 1),
    keywords: ['Landmark'],
  },
  // ── Set 3: Worldwalker ────────────────────────────────────────────────────
  {
    name: 'Bard',
    type: 'Champion',
    rarity: 'Legendary' as LolRarity,
    region: 'Bandle City' as LolRegion,
    setId: 'set-3',
    setName: 'Worldwalker',
    setVersion: '3.0',
    cost: 3, attack: 2, health: 4,
    description: 'When Bard is summoned, add 2 Chimes to your deck. Collect 20 Chimes to level up.',
    imageUrl: ART('Bard'),
    keywords: ['Wanderer', 'Chime'],
  },
  {
    name: 'Sett',
    type: 'Champion',
    rarity: 'Legendary' as LolRarity,
    region: 'Ionia' as LolRegion,
    setId: 'set-3',
    setName: 'Worldwalker',
    setVersion: '3.0',
    cost: 4, attack: 5, health: 4,
    description: 'Tough. When Sett takes 3+ damage at once, he deals that much back to the attacker.',
    imageUrl: ART('Sett'),
    keywords: ['Tough', 'Pit Fighter'],
  },
  {
    name: 'Pantheon',
    type: 'Champion',
    rarity: 'Legendary' as LolRarity,
    region: 'Targon' as LolRegion,
    setId: 'set-3',
    setName: 'Worldwalker',
    setVersion: '3.0',
    cost: 5, attack: 5, health: 4,
    description: 'Challenger. When Pantheon damages the enemy Nexus, level up.',
    flavorText: '"I am become war."',
    imageUrl: ART('Pantheon'),
    keywords: ['Challenger', 'Barrier', 'Fury'],
  },
  {
    name: 'Illaoi',
    type: 'Champion',
    rarity: 'Epic' as LolRarity,
    region: 'Bilgewater' as LolRegion,
    setId: 'set-3',
    setName: 'Worldwalker',
    setVersion: '3.0',
    cost: 5, attack: 4, health: 6,
    description: 'When you summon a Tentacle, deal 1 to all enemies.',
    imageUrl: ART('Illaoi'),
    keywords: ['Deep', 'Brash'],
  },
  {
    name: 'Tentacle Smash',
    type: 'Spell',
    rarity: 'Common' as LolRarity,
    region: 'Bilgewater' as LolRegion,
    setId: 'set-3',
    setName: 'Worldwalker',
    setVersion: '3.0',
    cost: 3,
    description: 'Deal 5 to a unit. Summon a Tentacle.',
    imageUrl: ART('Illaoi', 1),
    keywords: ['Slow'],
  },
  // ── Set 4: Forces of Beyond ───────────────────────────────────────────────
  {
    name: 'Naafiri',
    type: 'Champion',
    rarity: 'Legendary' as LolRarity,
    region: 'Shurima' as LolRegion,
    setId: 'set-4',
    setName: 'Forces of Beyond',
    setVersion: '4.0',
    cost: 3, attack: 3, health: 2,
    description: 'Quick Attack. When Naafiri kills a unit, summon a Packmate.',
    imageUrl: ART('Naafiri'),
    keywords: ['Quick Attack', 'Pack Leader'],
  },
  {
    name: 'Briar',
    type: 'Champion',
    rarity: 'Legendary' as LolRarity,
    region: 'Noxus' as LolRegion,
    setId: 'set-4',
    setName: 'Forces of Beyond',
    setVersion: '4.0',
    cost: 4, attack: 6, health: 3,
    description: 'Overwhelm. Briar attacks every round. When Briar kills a unit, heal 3.',
    imageUrl: ART('Briar'),
    keywords: ['Overwhelm', 'Bloodthirst'],
  },
  {
    name: "Rek'Sai",
    type: 'Champion',
    rarity: 'Legendary' as LolRarity,
    region: 'Void' as LolRegion,
    setId: 'set-4',
    setName: 'Forces of Beyond',
    setVersion: '4.0',
    cost: 5, attack: 6, health: 4,
    description: "Overwhelm. Burrow: can't be blocked. Unburrow: gains +3/+0.",
    imageUrl: ART('RekSai'),
    keywords: ['Overwhelm', 'Burrow'],
  },
  {
    name: 'Ancient Hourglass',
    type: 'Equipment',
    rarity: 'Epic' as LolRarity,
    region: 'Shurima' as LolRegion,
    setId: 'set-4',
    setName: 'Forces of Beyond',
    setVersion: '4.0',
    cost: 2,
    description: "Equip to an ally. Equipped unit gains Stasis — can't be targeted or damaged.",
    imageUrl: ART('Zilean'),
    keywords: ['Equipment', 'Stasis'],
  },
  {
    name: 'Void Rift',
    type: 'Spell',
    rarity: 'Rare' as LolRarity,
    region: 'Void' as LolRegion,
    setId: 'set-4',
    setName: 'Forces of Beyond',
    setVersion: '4.0',
    cost: 4,
    description: 'Summon 2 Voidspawn. Deal 1 to all enemies for each Voidling you have.',
    imageUrl: ART('KhaZix'),
    keywords: ['Slow'],
  },
];

// Define which print types each card gets — same base card, different versions
const PRINT_SCHEDULES: Record<string, Array<{ printType: PrintType; cardNumber: string }>> = {
  // Legendaries get more printings
  Jinx:             [{ printType: 'Normal', cardNumber: '001/180' }, { printType: 'Foil', cardNumber: '001F/180' }, { printType: 'Full Art', cardNumber: 'FA-001' }, { printType: 'Alternate Art', cardNumber: 'AA-001' }],
  Lux:              [{ printType: 'Normal', cardNumber: '002/180' }, { printType: 'Foil', cardNumber: '002F/180' }, { printType: 'Full Art', cardNumber: 'FA-002' }],
  Darius:           [{ printType: 'Normal', cardNumber: '003/180' }, { printType: 'Foil', cardNumber: '003F/180' }, { printType: 'First Edition', cardNumber: '003/180★' }],
  Ashe:             [{ printType: 'Normal', cardNumber: '004/180' }, { printType: 'Foil', cardNumber: '004F/180' }],
  Ezreal:           [{ printType: 'Normal', cardNumber: '005/180' }, { printType: 'Foil', cardNumber: '005F/180' }, { printType: 'Promo', cardNumber: 'P-005' }],
  Garen:            [{ printType: 'Normal', cardNumber: '006/180' }, { printType: 'Foil', cardNumber: '006F/180' }],
  Vi:               [{ printType: 'Normal', cardNumber: '007/180' }, { printType: 'Foil', cardNumber: '007F/180' }],
  'Mystic Shot':    [{ printType: 'Normal', cardNumber: '050/180' }, { printType: 'Foil', cardNumber: '050F/180' }],
  Decimate:         [{ printType: 'Normal', cardNumber: '051/180' }],
  "Anivia's Eggblock": [{ printType: 'Normal', cardNumber: '080/180' }, { printType: 'Holo', cardNumber: '080H/180' }],
  Leona:            [{ printType: 'Normal', cardNumber: '001/160' }, { printType: 'Foil', cardNumber: '001F/160' }, { printType: 'Full Art', cardNumber: 'FA-001' }],
  Diana:            [{ printType: 'Normal', cardNumber: '002/160' }, { printType: 'Foil', cardNumber: '002F/160' }],
  Malphite:         [{ printType: 'Normal', cardNumber: '003/160' }, { printType: 'Foil', cardNumber: '003F/160' }, { printType: 'First Edition', cardNumber: '003/160★' }],
  Soraka:           [{ printType: 'Normal', cardNumber: '040/160' }, { printType: 'Holo', cardNumber: '040H/160' }],
  'Cosmic Inspiration': [{ printType: 'Normal', cardNumber: '070/160' }],
  'The Grand Plaza': [{ printType: 'Normal', cardNumber: '090/160' }, { printType: 'Holo', cardNumber: '090H/160' }],
  Bard:             [{ printType: 'Normal', cardNumber: '001/140' }, { printType: 'Foil', cardNumber: '001F/140' }, { printType: 'Secret Rare', cardNumber: 'SR-001' }],
  Sett:             [{ printType: 'Normal', cardNumber: '002/140' }, { printType: 'Foil', cardNumber: '002F/140' }],
  Pantheon:         [{ printType: 'Normal', cardNumber: '003/140' }, { printType: 'Foil', cardNumber: '003F/140' }, { printType: 'Alternate Art', cardNumber: 'AA-003' }],
  Illaoi:           [{ printType: 'Normal', cardNumber: '010/140' }, { printType: 'Holo', cardNumber: '010H/140' }],
  'Tentacle Smash': [{ printType: 'Normal', cardNumber: '060/140' }],
  Naafiri:          [{ printType: 'Normal', cardNumber: '001/120' }, { printType: 'Foil', cardNumber: '001F/120' }],
  Briar:            [{ printType: 'Normal', cardNumber: '002/120' }, { printType: 'Foil', cardNumber: '002F/120' }, { printType: 'Full Art', cardNumber: 'FA-002' }],
  "Rek'Sai":        [{ printType: 'Normal', cardNumber: '003/120' }, { printType: 'Foil', cardNumber: '003F/120' }],
  'Ancient Hourglass': [{ printType: 'Normal', cardNumber: '050/120' }, { printType: 'Promo', cardNumber: 'P-050' }],
  'Void Rift':      [{ printType: 'Normal', cardNumber: '070/120' }],
};

// Flatten into individual card records (one per printing)
export const LOL_CARDS: LolCard[] = BASE_CARDS.flatMap((base) => {
  const printings = PRINT_SCHEDULES[base.name] ?? [{ printType: 'Normal' as PrintType, cardNumber: '???/???' }];
  const baseId = base.name.toLowerCase().replace(/[^a-z0-9]/g, '-');
  return make({ ...base, id: baseId }, printings);
});

export const LOL_ALL_TYPES    = [...new Set(LOL_CARDS.map((c) => c.type))].sort();
export const LOL_ALL_RARITIES = [...new Set(LOL_CARDS.map((c) => c.rarity))].sort();
export const LOL_ALL_REGIONS  = [...new Set(LOL_CARDS.map((c) => c.region))].sort();
export const LOL_ALL_SETS     = Object.entries(LOL_SETS).map(([id, s]) => ({ id, ...s }));
export const LOL_ALL_PRINTS   = [...new Set(LOL_CARDS.map((c) => c.printType))].sort();
